# Generated by Django 4.2.4 on 2023-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_link_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_link',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortened_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
