# Generated by Django 4.2.4 on 2023-08-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_link_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='created',
            new_name='created_at',
        ),
    ]
