# Generated by Django 4.2.4 on 2023-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_link_original_link_alter_link_shortened_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortened_link',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
